Add ONS module
alibabacloud-automation/terraform-alicloud-ons pull request #1
Opened 2020-07-09 07:12 UTC by supercym

Add ONS module.
This module can create Apache RocketMQ related components on Alibaba Cloud.

2020-07-09 12:38 UTC, zql-tqy commented on README-CN.md
> +    // existing_instance_id = "MQ_INST_1234567890_AbcDefG"
这个做个脱敏处理，把后几位隐掉

2020-07-09 12:38 UTC, zql-tqy commented on README-CN.md
> +    profile            = "Your-Profile-Name"
这个格式调整齐吧

2020-07-09 12:38 UTC, zql-tqy commented on README-CN.md
> +    // 如果'create_instance'设置为true，本module将会生成一个新的instance。true也是'create_instance'的默认值。
建议英文的前后各添加一个空格

2020-07-09 12:38 UTC, zql-tqy commented on README-CN.md
> +本 Module 要求使用 Terraform 0.12 和 阿里云 Provider 1.56.0+。
这个 provider 版本指产品发布的版本，默认为 1.56.0+

2020-07-09 12:38 UTC, zql-tqy commented on README.md
> +    // existing_instance_id = "MQ_INST_1234567890_AbcDefG"
和中文 readme 中的处理方法一致

2020-07-09 12:38 UTC, zql-tqy commented on examples/complete/main.tf
> +provider "alicloud" {
添加一个 profile 变量
variable "profile" {
  default = "default"
}
provider "alicloud" {
  region  = var.region
  profile = var.profile
}

2020-07-09 12:38 UTC, zql-tqy commented on examples/complete/outputs.tf
> +output "instance_name" {
所有的 output 的名称前面都添加一个 this_，例如  this_instance_name

2020-07-09 12:38 UTC, zql-tqy commented on examples/complete/outputs.tf
> +  description = "Name of ONS Group."
The list ids of ONS Group. 这种体现出是个 list

2020-07-09 12:38 UTC, zql-tqy commented on modules/group/variables.tf
> +variable "instance_id" {
缺少 Type，非必填可指定默认值为“”

2020-07-09 12:38 UTC, zql-tqy commented on modules/instance/variables.tf
> +  description = "Name of ONS Instance. Two instances on a single account in the same region cannot have the same name and the number of instances in the same region cannot exceed 8. The length must b
缺少 type 和 default，必填可不设置 default

2020-07-09 12:38 UTC, zql-tqy commented on main.tf
> +module "instance" {
在主 main 中也直接定义 resource 吧，不用调用子 module

2020-07-10 06:09 UTC, supercym commented on README-CN.md
> +    // existing_instance_id = "MQ_INST_1234567890_AbcDefG"
done

2020-07-10 06:09 UTC, supercym commented on README.md
> +    // existing_instance_id = "MQ_INST_1234567890_AbcDefG"
ok

2020-07-10 06:14 UTC, supercym commented on README-CN.md
> +本 Module 要求使用 Terraform 0.12 和 阿里云 Provider 1.56.0+。
The version of ons related resource is earlier than 1.56.0

2020-07-10 06:16 UTC, supercym commented on examples/complete/main.tf
> +provider "alicloud" {
done

2020-07-10 06:16 UTC, supercym commented on examples/complete/outputs.tf
> +output "instance_name" {
done

2020-07-10 06:16 UTC, supercym commented on examples/complete/outputs.tf
> +  description = "Name of ONS Group."
ok

2020-07-10 06:16 UTC, supercym commented on modules/instance/variables.tf
> +  description = "Name of ONS Instance. Two instances on a single account in the same region cannot have the same name and the number of instances in the same region cannot exceed 8. The length must b
done

2020-07-10 11:44 UTC, zql-tqy commented on modules/group/README.md
> +# Alibaba Cloud Redis-Accounts
这个没有改，内容也不对

2020-07-10 11:44 UTC, zql-tqy commented on modules/instance/README.md
> +# Alibaba Cloud Redis-Accounts
这个也是没有修改

2020-07-10 11:44 UTC, zql-tqy commented on modules/topic/README.md
> +# Alibaba Cloud Redis-Accounts
还有这个

2020-07-18 13:23 UTC, xiaozhu36 requested changes

2020-07-18 13:23 UTC, xiaozhu36 commented on main.tf
> +  count       = length(var.group_ids)
count 应该用一个单独的常量来控制，比如： count  = var.number_of_group

2020-07-18 13:23 UTC, xiaozhu36 commented on main.tf
> +  count        = length(var.topics)
类似

2020-07-18 13:23 UTC, xiaozhu36 commented on variables.tf
> +  description = "The list names of ONS Group. Two groups on a single instance cannot have the same name and the name must start with 'GID-' or 'GID_'. The length must be 7 to 64 characters."
group_ids  与 list names of ONS Group 语意不符

2020-07-18 13:23 UTC, xiaozhu36 commented on variables.tf
> +  description = "The list names of ONS Topic. Two topics on a single instance cannot have the same name and the name cannot start with 'GID' or 'CID'. The length cannot exceed 64 characters."
topics 应该改成 topic_names

2020-07-22 01:48 UTC, xiaozhu36 approved these changes

2020-07-22 01:48 UTC, merged